project:
  type: website
  output-dir: docs

website:
  title: "Josh Persi"
  search: false
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/joshpersi
      - icon: bluesky
        href: https://bsky.app/profile/joshpersi.bsky.social
      - icon: linkedin
        href: https://www.linkedin.com/in/josh-persi
  
format: 
  html:
    engine: knitr
    highlight-style: nord
    theme: 
      light: style-light.scss
      dark: style-dark.scss
    code-link: true
    code-overflow: wrap
    respect-user-color-scheme: true

editor: source

