project:
  type: website
  output-dir: docs


website:
  title: "Josh Persi"
  search: false
  navbar:
    right:
      - about.qmd
      - icon: mastodon
        href: https://fosstodon.org/@joshpersi
        aria-label: Mastodon
      - icon: github
        href: https://github.com/joshpersi
      - icon: twitter-x
        href: https://x.com/joshuapersi
      - icon: linkedin
        href: https://www.linkedin.com/in/josh-persi
  
format:
  html:
    theme: cosmo
    css: styles.css

editor: source

