project:
  type: website

website:
  title: "Blog"
  navbar:
    right:
      - text: "About"
        file: about.qmd
      - icon: mastodon
        href: https://fosstodon.org/@joshpersi
      - icon: github
        href: https://github.com/josh-persi
  search: false
  page-footer:
    center: "Josh Persi {{< fa regular copyright >}} 2023"
    border: false
format:
  html:
    theme:
      - theme.scss
    css: styles.css
    # highlight-style: eiffel
